spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.89.30.145:3306/idol?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: biscuit
    password: Jiushizheme6?

    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      test-on-borrow: true
      stat-view-servlet:
        login-password: druid
        login-username: druid
        url-pattern: /druid

  redis:
    database: 0
    host: localhost
    port: 6379

mybatis:
  type-aliases-package: com.icybiscuit.idol.dao.entity
  mapper-locations: classpath:mapper/*.xml